--
-- PostgreSQL database dump
--

\restrict HL6qY3BaEmfwhSK1USatB6Tr8mVT6G5i1YkTfDtRR0KwQow3yKCfAn8nhuXLTz4

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.0

-- Started on 2026-02-13 19:18:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 49153)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5201 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 49154)
-- Name: activities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activities (
    id bigint NOT NULL,
    user_id bigint,
    type text NOT NULL,
    title text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.activities OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 49164)
-- Name: activities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 49165)
-- Name: approved_organizations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.approved_organizations (
    id bigint NOT NULL,
    registration_id bigint,
    user_id bigint,
    full_name text NOT NULL,
    address text NOT NULL,
    ogrn character varying(13) NOT NULL,
    registration_date date NOT NULL,
    director_fio text NOT NULL,
    director_inn character varying(12) NOT NULL,
    director_position text NOT NULL,
    contact_email text,
    contact_phone text,
    approved_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.approved_organizations OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 49180)
-- Name: approved_organizations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.approved_organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.approved_organizations_id_seq OWNER TO postgres;

--
-- TOC entry 5203 (class 0 OID 0)
-- Dependencies: 222
-- Name: approved_organizations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.approved_organizations_id_seq OWNED BY public.approved_organizations.id;


--
-- TOC entry 223 (class 1259 OID 49181)
-- Name: approved_schools; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.approved_schools (
    id bigint NOT NULL,
    full_name text NOT NULL,
    short_name text NOT NULL,
    inn text,
    ogrn text,
    ogrn_date date,
    address text,
    director_fio text,
    director_inn text,
    director_position text,
    contact_phone text,
    contact_email text,
    approved_at timestamp without time zone DEFAULT now() NOT NULL,
    approved_by bigint,
    region character varying(255) NOT NULL,
    user_id bigint,
    organization_id bigint
);


ALTER TABLE public.approved_schools OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 49192)
-- Name: approved_schools_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.approved_schools ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approved_schools_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 49193)
-- Name: jury_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jury_members (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    organization text,
    passport_series text,
    passport_number text,
    passport_issued_by text,
    passport_issued_date date,
    birthdate date
);


ALTER TABLE public.jury_members OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 49200)
-- Name: jury_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jury_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jury_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 49201)
-- Name: news; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.news (
    id bigint NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    author_role text,
    author_id bigint
);


ALTER TABLE public.news OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 81967)
-- Name: news_files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.news_files (
    id bigint NOT NULL,
    news_id bigint,
    file_name text,
    mime_type text,
    file_data bytea,
    uploaded_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.news_files OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 81966)
-- Name: news_files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.news_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.news_files_id_seq OWNER TO postgres;

--
-- TOC entry 5204 (class 0 OID 0)
-- Dependencies: 251
-- Name: news_files_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.news_files_id_seq OWNED BY public.news_files.id;


--
-- TOC entry 228 (class 1259 OID 49211)
-- Name: news_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 49212)
-- Name: olympiad_jury; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.olympiad_jury (
    id bigint NOT NULL,
    olympiad_id bigint NOT NULL,
    jury_member_id bigint NOT NULL,
    jury_role text NOT NULL
);


ALTER TABLE public.olympiad_jury OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 49221)
-- Name: olympiad_jury_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.olympiad_jury ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.olympiad_jury_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 49222)
-- Name: olympiad_participants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.olympiad_participants (
    id bigint NOT NULL,
    olympiad_id bigint NOT NULL,
    student_id bigint NOT NULL,
    score numeric(6,2),
    score_draft numeric,
    review_requested boolean DEFAULT false,
    review_reason text,
    review_requested_at timestamp with time zone
);


ALTER TABLE public.olympiad_participants OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 49228)
-- Name: olympiad_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.olympiad_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.olympiad_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 49229)
-- Name: olympiad_task_files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.olympiad_task_files (
    id bigint NOT NULL,
    olympiad_id bigint NOT NULL,
    file_name text NOT NULL,
    mime_type text,
    file_data bytea NOT NULL,
    uploaded_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.olympiad_task_files OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 49240)
-- Name: olympiad_task_files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.olympiad_task_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.olympiad_task_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 49241)
-- Name: olympiads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.olympiads (
    id bigint NOT NULL,
    school_id bigint,
    subject text NOT NULL,
    datetime timestamp without time zone,
    grades text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'upcoming'::text NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    organizer_id bigint,
    window_start timestamp without time zone,
    window_end timestamp without time zone,
    organization_id bigint,
    template_id bigint,
    results_published boolean DEFAULT false,
    results_published_at timestamp with time zone,
    CONSTRAINT olympiads_status_check CHECK ((status = ANY (ARRAY['upcoming'::text, 'ongoing'::text, 'completed'::text, 'cancelled'::text, 'archived'::text])))
);


ALTER TABLE public.olympiads OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 49256)
-- Name: olympiads_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.olympiads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.olympiads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 49257)
-- Name: organizer_registration_files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organizer_registration_files (
    id bigint NOT NULL,
    registration_id bigint NOT NULL,
    original_name text NOT NULL,
    stored_name text NOT NULL,
    file_size bigint DEFAULT 0 NOT NULL,
    uploaded_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.organizer_registration_files OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 49270)
-- Name: organizer_registration_files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.organizer_registration_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.organizer_registration_files_id_seq OWNER TO postgres;

--
-- TOC entry 5205 (class 0 OID 0)
-- Dependencies: 238
-- Name: organizer_registration_files_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.organizer_registration_files_id_seq OWNED BY public.organizer_registration_files.id;


--
-- TOC entry 239 (class 1259 OID 49271)
-- Name: organizer_registrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organizer_registrations (
    id bigint NOT NULL,
    full_name text NOT NULL,
    address text NOT NULL,
    ogrn character varying(13) NOT NULL,
    registration_date date NOT NULL,
    director_fio text NOT NULL,
    director_inn character varying(12) NOT NULL,
    director_position text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    rejection_reason text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    processed_by bigint,
    processed_at timestamp without time zone,
    contact_email text,
    contact_phone text,
    CONSTRAINT organizer_registrations_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])))
);


ALTER TABLE public.organizer_registrations OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 49289)
-- Name: organizer_registrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.organizer_registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.organizer_registrations_id_seq OWNER TO postgres;

--
-- TOC entry 5206 (class 0 OID 0)
-- Dependencies: 240
-- Name: organizer_registrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.organizer_registrations_id_seq OWNED BY public.organizer_registrations.id;


--
-- TOC entry 254 (class 1259 OID 90310)
-- Name: organizer_school_documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organizer_school_documents (
    id bigint NOT NULL,
    school_id bigint NOT NULL,
    original_name text NOT NULL,
    stored_name text NOT NULL,
    file_size bigint DEFAULT 0 NOT NULL,
    uploaded_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.organizer_school_documents OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 90309)
-- Name: organizer_school_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.organizer_school_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.organizer_school_documents_id_seq OWNER TO postgres;

--
-- TOC entry 5207 (class 0 OID 0)
-- Dependencies: 253
-- Name: organizer_school_documents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.organizer_school_documents_id_seq OWNED BY public.organizer_school_documents.id;


--
-- TOC entry 241 (class 1259 OID 49290)
-- Name: participant_work_files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.participant_work_files (
    id bigint NOT NULL,
    olympiad_id bigint NOT NULL,
    student_id bigint NOT NULL,
    file_name text NOT NULL,
    mime_type text,
    file_data bytea NOT NULL,
    uploaded_at timestamp without time zone DEFAULT now() NOT NULL,
    is_published boolean DEFAULT true
);


ALTER TABLE public.participant_work_files OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 49302)
-- Name: participant_work_files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.participant_work_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.participant_work_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 49303)
-- Name: school_olympiads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.school_olympiads (
    id bigint NOT NULL,
    school_id bigint NOT NULL,
    olympiad_id bigint NOT NULL,
    scheduled_at timestamp without time zone NOT NULL,
    status text DEFAULT 'planned'::text NOT NULL,
    created_by_user_id bigint,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    grades text NOT NULL,
    description text,
    CONSTRAINT school_olympiads_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'approved'::text, 'rejected'::text, 'completed'::text, 'cancelled'::text])))
);


ALTER TABLE public.school_olympiads OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 49318)
-- Name: school_olympiads_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.school_olympiads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_olympiads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 81921)
-- Name: support_chats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.support_chats (
    id integer NOT NULL,
    user_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_message_at timestamp with time zone,
    guest_name text
);


ALTER TABLE public.support_chats OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 81920)
-- Name: support_chats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.support_chats_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.support_chats_id_seq OWNER TO postgres;

--
-- TOC entry 5208 (class 0 OID 0)
-- Dependencies: 247
-- Name: support_chats_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.support_chats_id_seq OWNED BY public.support_chats.id;


--
-- TOC entry 250 (class 1259 OID 81937)
-- Name: support_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.support_messages (
    id integer NOT NULL,
    chat_id integer NOT NULL,
    sender_id integer,
    sender_role text NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_read boolean DEFAULT false NOT NULL
);


ALTER TABLE public.support_messages OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 81936)
-- Name: support_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.support_messages_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.support_messages_id_seq OWNER TO postgres;

--
-- TOC entry 5209 (class 0 OID 0)
-- Dependencies: 249
-- Name: support_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.support_messages_id_seq OWNED BY public.support_messages.id;


--
-- TOC entry 245 (class 1259 OID 49335)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username text NOT NULL,
    password text NOT NULL,
    role text NOT NULL,
    full_name text,
    email text,
    snils text,
    age integer,
    grade integer,
    school_id bigint,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    must_change_password boolean DEFAULT true NOT NULL,
    organization_id bigint,
    CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'moderator'::text, 'organizer'::text, 'student'::text, 'expert'::text, 'school'::text, 'school_coordinator'::text])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 49349)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4895 (class 2604 OID 49350)
-- Name: approved_organizations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approved_organizations ALTER COLUMN id SET DEFAULT nextval('public.approved_organizations_id_seq'::regclass);


--
-- TOC entry 4922 (class 2604 OID 81970)
-- Name: news_files id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news_files ALTER COLUMN id SET DEFAULT nextval('public.news_files_id_seq'::regclass);


--
-- TOC entry 4905 (class 2604 OID 49351)
-- Name: organizer_registration_files id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizer_registration_files ALTER COLUMN id SET DEFAULT nextval('public.organizer_registration_files_id_seq'::regclass);


--
-- TOC entry 4908 (class 2604 OID 49352)
-- Name: organizer_registrations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizer_registrations ALTER COLUMN id SET DEFAULT nextval('public.organizer_registrations_id_seq'::regclass);


--
-- TOC entry 4924 (class 2604 OID 90313)
-- Name: organizer_school_documents id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizer_school_documents ALTER COLUMN id SET DEFAULT nextval('public.organizer_school_documents_id_seq'::regclass);


--
-- TOC entry 4917 (class 2604 OID 81924)
-- Name: support_chats id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.support_chats ALTER COLUMN id SET DEFAULT nextval('public.support_chats_id_seq'::regclass);


--
-- TOC entry 4919 (class 2604 OID 81940)
-- Name: support_messages id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.support_messages ALTER COLUMN id SET DEFAULT nextval('public.support_messages_id_seq'::regclass);


--
-- TOC entry 5160 (class 0 OID 49154)
-- Dependencies: 219
-- Data for Name: activities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.activities (id, user_id, type, title, created_at) FROM stdin;
1	1	application_processed	Организация «Управление по делам образования и здравоохранения администрации Курского района Курской области» была одобрена и добавлена в систему	2026-02-13 15:51:47.203063
2	2	school_registered	Зарегистрировано образовательное учреждение «МБОУ "Рыльская СОШ №1"»	2026-02-13 15:53:39.932524
3	3	user_created	Добавлен координатор: Бобылев Дмитрий Иванович (Завуч)	2026-02-13 17:14:42.585357
4	3	user_created	Добавлен координатор: Бобылев Дмитрий Иванович (Завуч)	2026-02-13 17:47:26.154468
\.


--
-- TOC entry 5162 (class 0 OID 49165)
-- Dependencies: 221
-- Data for Name: approved_organizations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.approved_organizations (id, registration_id, user_id, full_name, address, ogrn, registration_date, director_fio, director_inn, director_position, contact_email, contact_phone, approved_at) FROM stdin;
1	1	2	Управление по делам образования и здравоохранения администрации Курского района Курской области	Курская область, г. Курск, ул. Белинского, д. 21	1064611001762	2006-01-20	Тулиёва Оксана Леонидовна	460500505009	Начальник управления	northerntigris@ya.ru	89969430743	2026-02-13 15:51:47.203063
\.


--
-- TOC entry 5164 (class 0 OID 49181)
-- Dependencies: 223
-- Data for Name: approved_schools; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.approved_schools (id, full_name, short_name, inn, ogrn, ogrn_date, address, director_fio, director_inn, director_position, contact_phone, contact_email, approved_at, approved_by, region, user_id, organization_id) FROM stdin;
1	МБОУ "Рыльская средняя общеобразовательная школа №1"	МБОУ "Рыльская СОШ №1"	462700684863	1204600008535	2026-01-28	Курская обл. г. Рыльск, ул. Луначарского, д.17	Бобылев Дмитрий Иванович	462700684863	Директор	555555	northerntigris@ya.ru	2026-02-13 15:53:39.932524	2	Курская область	3	1
\.


--
-- TOC entry 5166 (class 0 OID 49193)
-- Dependencies: 225
-- Data for Name: jury_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jury_members (id, user_id, organization, passport_series, passport_number, passport_issued_by, passport_issued_date, birthdate) FROM stdin;
\.


--
-- TOC entry 5168 (class 0 OID 49201)
-- Dependencies: 227
-- Data for Name: news; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.news (id, title, content, created_at, author_role, author_id) FROM stdin;
\.


--
-- TOC entry 5193 (class 0 OID 81967)
-- Dependencies: 252
-- Data for Name: news_files; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.news_files (id, news_id, file_name, mime_type, file_data, uploaded_at) FROM stdin;
\.


--
-- TOC entry 5170 (class 0 OID 49212)
-- Dependencies: 229
-- Data for Name: olympiad_jury; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.olympiad_jury (id, olympiad_id, jury_member_id, jury_role) FROM stdin;
\.


--
-- TOC entry 5172 (class 0 OID 49222)
-- Dependencies: 231
-- Data for Name: olympiad_participants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.olympiad_participants (id, olympiad_id, student_id, score, score_draft, review_requested, review_reason, review_requested_at) FROM stdin;
\.


--
-- TOC entry 5174 (class 0 OID 49229)
-- Dependencies: 233
-- Data for Name: olympiad_task_files; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.olympiad_task_files (id, olympiad_id, file_name, mime_type, file_data, uploaded_at) FROM stdin;
\.


--
-- TOC entry 5176 (class 0 OID 49241)
-- Dependencies: 235
-- Data for Name: olympiads; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.olympiads (id, school_id, subject, datetime, grades, description, status, created_at, organizer_id, window_start, window_end, organization_id, template_id, results_published, results_published_at) FROM stdin;
1	\N	Русский язык	\N	4-11		upcoming	2026-02-13 18:25:06.659672	2	2026-02-14 18:24:00	2026-02-18 18:24:00	1	\N	f	\N
2	1	Русский язык	2026-02-15 18:25:00	5-9		upcoming	2026-02-13 18:25:49.984093	2	2026-02-14 18:24:00	2026-02-18 18:24:00	1	1	f	\N
\.


--
-- TOC entry 5178 (class 0 OID 49257)
-- Dependencies: 237
-- Data for Name: organizer_registration_files; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.organizer_registration_files (id, registration_id, original_name, stored_name, file_size, uploaded_at) FROM stdin;
\.


--
-- TOC entry 5180 (class 0 OID 49271)
-- Dependencies: 239
-- Data for Name: organizer_registrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.organizer_registrations (id, full_name, address, ogrn, registration_date, director_fio, director_inn, director_position, status, rejection_reason, created_at, processed_by, processed_at, contact_email, contact_phone) FROM stdin;
1	Управление по делам образования и здравоохранения администрации Курского района Курской области	Курская область, г. Курск, ул. Белинского, д. 21	1064611001762	2006-01-20	Тулиёва Оксана Леонидовна	460500505009	Начальник управления	approved	\N	2026-02-13 15:51:03.721103	1	2026-02-13 15:51:47.203063	northerntigris@ya.ru	89969430743
\.


--
-- TOC entry 5195 (class 0 OID 90310)
-- Dependencies: 254
-- Data for Name: organizer_school_documents; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.organizer_school_documents (id, school_id, original_name, stored_name, file_size, uploaded_at) FROM stdin;
\.


--
-- TOC entry 5182 (class 0 OID 49290)
-- Dependencies: 241
-- Data for Name: participant_work_files; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.participant_work_files (id, olympiad_id, student_id, file_name, mime_type, file_data, uploaded_at, is_published) FROM stdin;
\.


--
-- TOC entry 5184 (class 0 OID 49303)
-- Dependencies: 243
-- Data for Name: school_olympiads; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.school_olympiads (id, school_id, olympiad_id, scheduled_at, status, created_by_user_id, created_at, grades, description) FROM stdin;
\.


--
-- TOC entry 5189 (class 0 OID 81921)
-- Dependencies: 248
-- Data for Name: support_chats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.support_chats (id, user_id, created_at, last_message_at, guest_name) FROM stdin;
1	\N	2026-02-13 19:08:00.651561+03	\N	Гость b744ca
\.


--
-- TOC entry 5191 (class 0 OID 81937)
-- Dependencies: 250
-- Data for Name: support_messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.support_messages (id, chat_id, sender_id, sender_role, message, created_at, is_read) FROM stdin;
\.


--
-- TOC entry 5186 (class 0 OID 49335)
-- Dependencies: 245
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, username, password, role, full_name, email, snils, age, grade, school_id, created_at, must_change_password, organization_id) FROM stdin;
1	admin	$2y$10$OmqMMwqamJByrzekEVB/UO.URIRBSPigtTdOgm.KBEFfswhqYdmxu	admin	Бобылев Дмитрий Иванович	northerntigris@ya.ru	\N	\N	\N	\N	2026-02-13 15:26:17.832563	t	\N
2	org1	$2y$10$FCkcOM.PXPC.5hqd/ThAVuMxZZuU/Pahl7aag7zQFEakWt3phtfs2	organizer	Тулиёва Оксана Леонидовна	\N	\N	\N	\N	\N	2026-02-13 15:51:47.203063	t	1
3	sch_northerntigris	$2y$10$ofiIdue0Zs/k/ZMq6Atm3ey2oTK/E8lcXjIgAY.4pPqk6SYmCwhIi	school	МБОУ "Рыльская средняя общеобразовательная школа №1"	northerntigris@ya.ru	\N	\N	\N	1	2026-02-13 15:53:39.932524	t	\N
5	coord_1770994045_1550	$2y$10$OsmwX3mGkil3Un9zwwDC.e9eVx./yfLkVSZhruyriPEYLzFlZTNW6	school_coordinator	Бобылев Дмитрий Иванович	northerntigris@ya.ru	00000000000	\N	\N	1	2026-02-13 17:47:25.514962	t	\N
\.


--
-- TOC entry 5210 (class 0 OID 0)
-- Dependencies: 220
-- Name: activities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.activities_id_seq', 4, true);


--
-- TOC entry 5211 (class 0 OID 0)
-- Dependencies: 222
-- Name: approved_organizations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.approved_organizations_id_seq', 1, true);


--
-- TOC entry 5212 (class 0 OID 0)
-- Dependencies: 224
-- Name: approved_schools_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.approved_schools_id_seq', 1, true);


--
-- TOC entry 5213 (class 0 OID 0)
-- Dependencies: 226
-- Name: jury_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jury_members_id_seq', 1, false);


--
-- TOC entry 5214 (class 0 OID 0)
-- Dependencies: 251
-- Name: news_files_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.news_files_id_seq', 1, false);


--
-- TOC entry 5215 (class 0 OID 0)
-- Dependencies: 228
-- Name: news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.news_id_seq', 1, false);


--
-- TOC entry 5216 (class 0 OID 0)
-- Dependencies: 230
-- Name: olympiad_jury_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.olympiad_jury_id_seq', 1, false);


--
-- TOC entry 5217 (class 0 OID 0)
-- Dependencies: 232
-- Name: olympiad_participants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.olympiad_participants_id_seq', 1, false);


--
-- TOC entry 5218 (class 0 OID 0)
-- Dependencies: 234
-- Name: olympiad_task_files_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.olympiad_task_files_id_seq', 1, false);


--
-- TOC entry 5219 (class 0 OID 0)
-- Dependencies: 236
-- Name: olympiads_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.olympiads_id_seq', 2, true);


--
-- TOC entry 5220 (class 0 OID 0)
-- Dependencies: 238
-- Name: organizer_registration_files_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.organizer_registration_files_id_seq', 1, false);


--
-- TOC entry 5221 (class 0 OID 0)
-- Dependencies: 240
-- Name: organizer_registrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.organizer_registrations_id_seq', 1, true);


--
-- TOC entry 5222 (class 0 OID 0)
-- Dependencies: 253
-- Name: organizer_school_documents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.organizer_school_documents_id_seq', 1, false);


--
-- TOC entry 5223 (class 0 OID 0)
-- Dependencies: 242
-- Name: participant_work_files_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.participant_work_files_id_seq', 1, false);


--
-- TOC entry 5224 (class 0 OID 0)
-- Dependencies: 244
-- Name: school_olympiads_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.school_olympiads_id_seq', 1, false);


--
-- TOC entry 5225 (class 0 OID 0)
-- Dependencies: 247
-- Name: support_chats_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.support_chats_id_seq', 1, true);


--
-- TOC entry 5226 (class 0 OID 0)
-- Dependencies: 249
-- Name: support_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.support_messages_id_seq', 1, false);


--
-- TOC entry 5227 (class 0 OID 0)
-- Dependencies: 246
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- TOC entry 4932 (class 2606 OID 49354)
-- Name: activities activities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);


--
-- TOC entry 4934 (class 2606 OID 49356)
-- Name: approved_organizations approved_organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approved_organizations
    ADD CONSTRAINT approved_organizations_pkey PRIMARY KEY (id);


--
-- TOC entry 4936 (class 2606 OID 49358)
-- Name: approved_organizations approved_organizations_registration_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approved_organizations
    ADD CONSTRAINT approved_organizations_registration_id_key UNIQUE (registration_id);


--
-- TOC entry 4938 (class 2606 OID 49360)
-- Name: approved_organizations approved_organizations_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approved_organizations
    ADD CONSTRAINT approved_organizations_user_id_key UNIQUE (user_id);


--
-- TOC entry 4941 (class 2606 OID 49362)
-- Name: approved_schools approved_schools_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approved_schools
    ADD CONSTRAINT approved_schools_pkey PRIMARY KEY (id);


--
-- TOC entry 4944 (class 2606 OID 49366)
-- Name: jury_members jury_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jury_members
    ADD CONSTRAINT jury_members_pkey PRIMARY KEY (id);


--
-- TOC entry 4946 (class 2606 OID 49368)
-- Name: jury_members jury_members_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jury_members
    ADD CONSTRAINT jury_members_user_id_key UNIQUE (user_id);


--
-- TOC entry 4983 (class 2606 OID 81977)
-- Name: news_files news_files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news_files
    ADD CONSTRAINT news_files_pkey PRIMARY KEY (id);


--
-- TOC entry 4948 (class 2606 OID 49370)
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- TOC entry 4950 (class 2606 OID 49372)
-- Name: olympiad_jury olympiad_jury_olympiad_id_jury_member_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiad_jury
    ADD CONSTRAINT olympiad_jury_olympiad_id_jury_member_id_key UNIQUE (olympiad_id, jury_member_id);


--
-- TOC entry 4952 (class 2606 OID 49374)
-- Name: olympiad_jury olympiad_jury_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiad_jury
    ADD CONSTRAINT olympiad_jury_pkey PRIMARY KEY (id);


--
-- TOC entry 4954 (class 2606 OID 49376)
-- Name: olympiad_participants olympiad_participants_olympiad_id_student_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiad_participants
    ADD CONSTRAINT olympiad_participants_olympiad_id_student_id_key UNIQUE (olympiad_id, student_id);


--
-- TOC entry 4956 (class 2606 OID 49378)
-- Name: olympiad_participants olympiad_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiad_participants
    ADD CONSTRAINT olympiad_participants_pkey PRIMARY KEY (id);


--
-- TOC entry 4958 (class 2606 OID 49380)
-- Name: olympiad_task_files olympiad_task_files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiad_task_files
    ADD CONSTRAINT olympiad_task_files_pkey PRIMARY KEY (id);


--
-- TOC entry 4962 (class 2606 OID 49382)
-- Name: olympiads olympiads_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiads
    ADD CONSTRAINT olympiads_pkey PRIMARY KEY (id);


--
-- TOC entry 4965 (class 2606 OID 49384)
-- Name: organizer_registration_files organizer_registration_files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizer_registration_files
    ADD CONSTRAINT organizer_registration_files_pkey PRIMARY KEY (id);


--
-- TOC entry 4968 (class 2606 OID 49386)
-- Name: organizer_registrations organizer_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizer_registrations
    ADD CONSTRAINT organizer_registrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4985 (class 2606 OID 90325)
-- Name: organizer_school_documents organizer_school_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizer_school_documents
    ADD CONSTRAINT organizer_school_documents_pkey PRIMARY KEY (id);


--
-- TOC entry 4970 (class 2606 OID 49390)
-- Name: participant_work_files participant_work_files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participant_work_files
    ADD CONSTRAINT participant_work_files_pkey PRIMARY KEY (id);


--
-- TOC entry 4972 (class 2606 OID 49392)
-- Name: school_olympiads school_olympiads_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.school_olympiads
    ADD CONSTRAINT school_olympiads_pkey PRIMARY KEY (id);


--
-- TOC entry 4979 (class 2606 OID 81930)
-- Name: support_chats support_chats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.support_chats
    ADD CONSTRAINT support_chats_pkey PRIMARY KEY (id);


--
-- TOC entry 4981 (class 2606 OID 81951)
-- Name: support_messages support_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.support_messages
    ADD CONSTRAINT support_messages_pkey PRIMARY KEY (id);


--
-- TOC entry 4975 (class 2606 OID 49396)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4977 (class 2606 OID 49398)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 4939 (class 1259 OID 49399)
-- Name: idx_approved_org_approved_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_approved_org_approved_at ON public.approved_organizations USING btree (approved_at DESC);


--
-- TOC entry 4942 (class 1259 OID 49400)
-- Name: idx_approved_schools_organization_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_approved_schools_organization_id ON public.approved_schools USING btree (organization_id);


--
-- TOC entry 4959 (class 1259 OID 49401)
-- Name: idx_olympiads_organization_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_olympiads_organization_id ON public.olympiads USING btree (organization_id);


--
-- TOC entry 4960 (class 1259 OID 57349)
-- Name: idx_olympiads_template_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_olympiads_template_id ON public.olympiads USING btree (template_id);


--
-- TOC entry 4963 (class 1259 OID 49402)
-- Name: idx_organizer_reg_files_registration_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_organizer_reg_files_registration_id ON public.organizer_registration_files USING btree (registration_id);


--
-- TOC entry 4966 (class 1259 OID 49403)
-- Name: idx_organizer_registrations_status_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_organizer_registrations_status_created ON public.organizer_registrations USING btree (status, created_at DESC);


--
-- TOC entry 4973 (class 1259 OID 49404)
-- Name: ux_school_olympiads_school_olympiad; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_school_olympiads_school_olympiad ON public.school_olympiads USING btree (school_id, olympiad_id);


--
-- TOC entry 4986 (class 2606 OID 49405)
-- Name: activities activities_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 4987 (class 2606 OID 49410)
-- Name: approved_organizations approved_organizations_registration_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approved_organizations
    ADD CONSTRAINT approved_organizations_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES public.organizer_registrations(id) ON DELETE SET NULL;


--
-- TOC entry 4988 (class 2606 OID 49415)
-- Name: approved_organizations approved_organizations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approved_organizations
    ADD CONSTRAINT approved_organizations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 4989 (class 2606 OID 49420)
-- Name: approved_schools approved_schools_approved_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approved_schools
    ADD CONSTRAINT approved_schools_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 4990 (class 2606 OID 49430)
-- Name: approved_schools approved_schools_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approved_schools
    ADD CONSTRAINT approved_schools_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5003 (class 2606 OID 49435)
-- Name: school_olympiads fk_school_olympiads_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.school_olympiads
    ADD CONSTRAINT fk_school_olympiads_created_by FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5004 (class 2606 OID 49440)
-- Name: school_olympiads fk_school_olympiads_olympiad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.school_olympiads
    ADD CONSTRAINT fk_school_olympiads_olympiad FOREIGN KEY (olympiad_id) REFERENCES public.olympiads(id) ON DELETE CASCADE;


--
-- TOC entry 5005 (class 2606 OID 49445)
-- Name: school_olympiads fk_school_olympiads_school; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.school_olympiads
    ADD CONSTRAINT fk_school_olympiads_school FOREIGN KEY (school_id) REFERENCES public.approved_schools(id) ON DELETE CASCADE;


--
-- TOC entry 5006 (class 2606 OID 49450)
-- Name: users fk_users_school_approved; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_school_approved FOREIGN KEY (school_id) REFERENCES public.approved_schools(id) ON DELETE SET NULL;


--
-- TOC entry 4991 (class 2606 OID 49455)
-- Name: jury_members jury_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jury_members
    ADD CONSTRAINT jury_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5011 (class 2606 OID 81978)
-- Name: news_files news_files_news_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news_files
    ADD CONSTRAINT news_files_news_id_fkey FOREIGN KEY (news_id) REFERENCES public.news(id) ON DELETE CASCADE;


--
-- TOC entry 4992 (class 2606 OID 49460)
-- Name: olympiad_jury olympiad_jury_jury_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiad_jury
    ADD CONSTRAINT olympiad_jury_jury_member_id_fkey FOREIGN KEY (jury_member_id) REFERENCES public.jury_members(id) ON DELETE CASCADE;


--
-- TOC entry 4993 (class 2606 OID 49465)
-- Name: olympiad_jury olympiad_jury_olympiad_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiad_jury
    ADD CONSTRAINT olympiad_jury_olympiad_id_fkey FOREIGN KEY (olympiad_id) REFERENCES public.olympiads(id) ON DELETE CASCADE;


--
-- TOC entry 4994 (class 2606 OID 49470)
-- Name: olympiad_participants olympiad_participants_olympiad_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiad_participants
    ADD CONSTRAINT olympiad_participants_olympiad_id_fkey FOREIGN KEY (olympiad_id) REFERENCES public.olympiads(id) ON DELETE CASCADE;


--
-- TOC entry 4995 (class 2606 OID 49475)
-- Name: olympiad_participants olympiad_participants_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiad_participants
    ADD CONSTRAINT olympiad_participants_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 4996 (class 2606 OID 49480)
-- Name: olympiad_task_files olympiad_task_files_olympiad_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiad_task_files
    ADD CONSTRAINT olympiad_task_files_olympiad_id_fkey FOREIGN KEY (olympiad_id) REFERENCES public.olympiads(id) ON DELETE CASCADE;


--
-- TOC entry 4997 (class 2606 OID 57350)
-- Name: olympiads olympiads_school_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiads
    ADD CONSTRAINT olympiads_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.approved_schools(id) ON DELETE CASCADE;


--
-- TOC entry 4998 (class 2606 OID 57344)
-- Name: olympiads olympiads_template_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.olympiads
    ADD CONSTRAINT olympiads_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.olympiads(id) ON DELETE SET NULL;


--
-- TOC entry 4999 (class 2606 OID 49490)
-- Name: organizer_registration_files organizer_registration_files_registration_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizer_registration_files
    ADD CONSTRAINT organizer_registration_files_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES public.organizer_registrations(id) ON DELETE CASCADE;


--
-- TOC entry 5000 (class 2606 OID 49495)
-- Name: organizer_registrations organizer_registrations_processed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizer_registrations
    ADD CONSTRAINT organizer_registrations_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5012 (class 2606 OID 90326)
-- Name: organizer_school_documents organizer_school_documents_school_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizer_school_documents
    ADD CONSTRAINT organizer_school_documents_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.approved_schools(id) ON DELETE CASCADE;


--
-- TOC entry 5001 (class 2606 OID 49500)
-- Name: participant_work_files participant_work_files_olympiad_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participant_work_files
    ADD CONSTRAINT participant_work_files_olympiad_id_fkey FOREIGN KEY (olympiad_id) REFERENCES public.olympiads(id) ON DELETE CASCADE;


--
-- TOC entry 5002 (class 2606 OID 49505)
-- Name: participant_work_files participant_work_files_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.participant_work_files
    ADD CONSTRAINT participant_work_files_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5008 (class 2606 OID 81931)
-- Name: support_chats support_chats_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.support_chats
    ADD CONSTRAINT support_chats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5009 (class 2606 OID 81952)
-- Name: support_messages support_messages_chat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.support_messages
    ADD CONSTRAINT support_messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.support_chats(id) ON DELETE CASCADE;


--
-- TOC entry 5010 (class 2606 OID 81957)
-- Name: support_messages support_messages_sender_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.support_messages
    ADD CONSTRAINT support_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5007 (class 2606 OID 49515)
-- Name: users users_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.approved_organizations(id) ON DELETE SET NULL;


--
-- TOC entry 5202 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


-- Completed on 2026-02-13 19:18:52

--
-- PostgreSQL database dump complete
--

\unrestrict HL6qY3BaEmfwhSK1USatB6Tr8mVT6G5i1YkTfDtRR0KwQow3yKCfAn8nhuXLTz4

